### ISSUE TITLE
SharpHound Version 2.0 uses JSON as output format

### ISSUE THREAD

**Issue by cyb3rwr3ck** [fox-it/Invoke-ACLPwn#3]
This renders Invoke-ACLPwn useless in its current behavior when used in conjunction with an recent version of SharpHound

**Comment by dirkjanm** [comment]
Correct, at this point in time you should keep using 1.5, there haven't been many fixes in 2.0 that will impact the working of Aclpwn as far as I'm aware. We'll make the tool compatible with 2.0 asap.

**Comment by rindert-fox** [comment]
Hi there,

Thanks, we've updated Invoke-ACLpwn. It now supports both csv as well as json files.
